import type {
  City,
  EarningClaim,
  Follow,
  MentorOffer,
  Role,
  SavedItem,
  User,
  VerificationDoc,
} from "@/lib/types";

export const demoCurrentUserId = "user-demo";

export const users: User[] = [
  {
    id: demoCurrentUserId,
    name: "Vincent La",
    anonymousName: "Verified Earner #1042",
    headline: "Building proof-backed career and business learning",
    avatarUrl: "",
    isAdmin: true,
    createdAt: "2026-01-15T12:00:00Z",
  },
  {
    id: "user-maya",
    name: "Maya Chen",
    anonymousName: "Senior Engineer #4821",
    headline: "Staff engineer turned negotiation mentor",
    createdAt: "2025-10-12T12:00:00Z",
  },
  {
    id: "user-darius",
    name: "Darius King",
    anonymousName: "Agency Operator #1190",
    headline: "B2B service agency founder",
    createdAt: "2025-09-18T12:00:00Z",
  },
  {
    id: "user-leah",
    name: "Leah Patel",
    anonymousName: "Options Trader #7334",
    headline: "Risk-first trading educator",
    createdAt: "2025-11-03T12:00:00Z",
  },
  {
    id: "user-omar",
    name: "Omar Reyes",
    anonymousName: "Consultant #2668",
    headline: "Independent cloud consultant",
    createdAt: "2025-08-28T12:00:00Z",
  },
  {
    id: "user-ivy",
    name: "Ivy Brooks",
    anonymousName: "Product Lead #9302",
    headline: "Product leader for AI workflow tools",
    createdAt: "2025-12-01T12:00:00Z",
  },
  {
    id: "user-nora",
    name: "Nora Ali",
    anonymousName: "Design Founder #5147",
    headline: "UX studio owner",
    createdAt: "2025-07-20T12:00:00Z",
  },
  {
    id: "user-caleb",
    name: "Caleb Stone",
    anonymousName: "Sales Operator #6711",
    headline: "B2B sales systems and enablement",
    createdAt: "2025-10-30T12:00:00Z",
  },
];

export const cities: City[] = [
  { name: "Los Angeles", state: "CA", country: "US" },
  { name: "New York", state: "NY", country: "US" },
  { name: "San Francisco", state: "CA", country: "US" },
  { name: "Austin", state: "TX", country: "US" },
  { name: "Chicago", state: "IL", country: "US" },
  { name: "Miami", state: "FL", country: "US" },
  { name: "Seattle", state: "WA", country: "US" },
  { name: "Denver", state: "CO", country: "US" },
];

export const roles: Role[] = [
  { title: "Software Engineer", category: "Engineering", claimType: "career" },
  { title: "Product Manager", category: "Product", claimType: "career" },
  { title: "UX Designer", category: "Design", claimType: "career" },
  { title: "Cloud Consultant", category: "Consulting", claimType: "freelance" },
  { title: "B2B Agency Owner", category: "Agency", claimType: "business" },
  { title: "Ecommerce Operator", category: "Ecommerce", claimType: "business" },
  { title: "Swing Trader", category: "Equities", claimType: "trading" },
  { title: "Options Trader", category: "Options", claimType: "trading" },
];

const salaryCurve = [
  108000, 116000, 121000, 126500, 132000, 137000, 142000, 148000, 153000, 159000, 164000, 171000,
  178000, 186000, 194000, 203000, 214000, 226000, 238000, 252000, 268000, 286000,
];

const generatedEngineerClaims: EarningClaim[] = salaryCurve.map((amount, index) => ({
  id: `claim-nyc-eng-${index + 1}`,
  userId: index % 2 === 0 ? "user-maya" : "user-ivy",
  claimType: "career",
  amountBasis: "annual_salary",
  amountCents: amount * 100,
  periodStart: "2025-01-01",
  periodEnd: "2025-12-31",
  role: "Software Engineer",
  category: "Engineering",
  city: "New York",
  state: "NY",
  country: "US",
  verificationStatus: "approved",
  verificationTier: 1,
  visibilityStatus: "public",
  displayAnonymously: true,
  shareSlug: `nyc-software-engineer-${amount}`,
  documentType: "w2",
  verifiedAt: "2026-02-01T12:00:00Z",
  createdAt: "2026-01-20T12:00:00Z",
  summary:
    "Annual career income verified from employment documents.",
  proofNote: "Document reviewed; raw document private and scheduled for deletion.",
  mentorReady: index === 17 || index === 21,
  riskFlags: [],
}));

export const earningClaims: EarningClaim[] = [
  ...generatedEngineerClaims,
  {
    id: "claim-maya-staff",
    userId: "user-maya",
    claimType: "career",
    amountBasis: "total_comp",
    amountCents: 31800000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "Staff Software Engineer",
    category: "Engineering",
    city: "San Francisco",
    state: "CA",
    country: "US",
    verificationStatus: "approved",
    verificationTier: 1,
    visibilityStatus: "public",
    displayAnonymously: false,
    shareSlug: "maya-staff-engineer-total-comp",
    documentType: "pay_stub",
    verifiedAt: "2026-01-18T12:00:00Z",
    createdAt: "2026-01-14T12:00:00Z",
    summary: "Staff engineering total compensation verified from pay documentation.",
    proofNote: "Document-reviewed total compensation, including salary and recurring equity vest.",
    mentorReady: true,
    riskFlags: [],
  },
  {
    id: "claim-darius-agency",
    userId: "user-darius",
    claimType: "business",
    amountBasis: "business_net_profit",
    amountCents: 21400000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "B2B Agency Owner",
    category: "Agency",
    city: "Austin",
    state: "TX",
    country: "US",
    verificationStatus: "approved",
    verificationTier: 1,
    visibilityStatus: "public",
    displayAnonymously: false,
    shareSlug: "darius-agency-net-profit-2025",
    documentType: "cpa_letter_pnl",
    verifiedAt: "2026-02-04T12:00:00Z",
    createdAt: "2026-01-27T12:00:00Z",
    summary: "Net profit verified from CPA letter and supporting profit and loss export.",
    proofNote: "Net profit verified; revenue-only claims are not eligible for this badge.",
    mentorReady: true,
    riskFlags: [],
  },
  {
    id: "claim-leah-pnl",
    userId: "user-leah",
    claimType: "trading",
    amountBasis: "realized_trading_pnl",
    amountCents: 9200000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "Options Trader",
    category: "Options",
    city: "Miami",
    state: "FL",
    country: "US",
    verificationStatus: "approved",
    verificationTier: 1,
    visibilityStatus: "public",
    displayAnonymously: false,
    shareSlug: "leah-realized-options-pnl-2025",
    documentType: "brokerage_statement",
    verifiedAt: "2026-02-12T12:00:00Z",
    createdAt: "2026-02-10T12:00:00Z",
    summary: "Realized P&L verified from brokerage statement for calendar year 2025.",
    proofNote: "Realized gains/losses only; unrealized gains and screenshots are not accepted.",
    mentorReady: true,
    riskFlags: ["Trading education only; no signals or guaranteed returns."],
  },
  {
    id: "claim-omar-consulting",
    userId: "user-omar",
    claimType: "freelance",
    amountBasis: "net_self_employment_income",
    amountCents: 17600000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "Cloud Consultant",
    category: "Consulting",
    city: "Denver",
    state: "CO",
    country: "US",
    verificationStatus: "approved",
    verificationTier: 1,
    visibilityStatus: "public",
    displayAnonymously: true,
    shareSlug: "cloud-consultant-net-income-2025",
    documentType: "tax_excerpt",
    verifiedAt: "2026-02-07T12:00:00Z",
    createdAt: "2026-01-30T12:00:00Z",
    summary: "Net self-employment income verified from tax excerpt and payout records.",
    proofNote: "Net income verified, not just gross client invoices.",
    mentorReady: true,
    riskFlags: [],
  },
  {
    id: "claim-nora-studio",
    userId: "user-nora",
    claimType: "business",
    amountBasis: "owner_income",
    amountCents: 13800000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "UX Studio Owner",
    category: "Design",
    city: "Los Angeles",
    state: "CA",
    country: "US",
    verificationStatus: "approved",
    verificationTier: 1,
    visibilityStatus: "public",
    displayAnonymously: false,
    shareSlug: "ux-studio-owner-income-2025",
    documentType: "k1",
    verifiedAt: "2026-02-02T12:00:00Z",
    createdAt: "2026-01-24T12:00:00Z",
    summary: "Owner income verified from K-1 and supporting business records.",
    proofNote: "Owner income verified; revenue is intentionally not displayed as income.",
    mentorReady: true,
    riskFlags: [],
  },
  {
    id: "claim-caleb-pending",
    userId: "user-caleb",
    claimType: "business",
    amountBasis: "business_net_profit",
    amountCents: 31000000,
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    role: "Sales Enablement Agency Owner",
    category: "Agency",
    city: "Chicago",
    state: "IL",
    country: "US",
    verificationStatus: "pending",
    verificationTier: 0,
    visibilityStatus: "pending_review",
    displayAnonymously: true,
    shareSlug: "sales-enablement-agency-review",
    documentType: "accounting_export",
    createdAt: "2026-03-01T12:00:00Z",
    summary: "Submitted accounting export for net profit verification.",
    proofNote: "Manual review required for all business income claims.",
    mentorReady: false,
    riskFlags: ["High net profit claim requires reviewer confirmation."],
  },
];

export const verificationDocs: VerificationDoc[] = [
  {
    id: "doc-caleb-review",
    claimId: "claim-caleb-pending",
    docType: "accounting_export",
    storagePath: "private/verification-docs/claim-caleb-pending/accounting-export.pdf",
    claimedAmountCents: 31000000,
    parsedAmountCents: 30480000,
    incomeMatch: true,
    outlierFlagged: true,
    parserStatus: "manual_required",
    parserNotes: ["Business claims always require manual review.", "Parsed amount appears within 10%."],
    reviewStatus: "pending",
    createdAt: "2026-03-01T12:08:00Z",
  },
];

export const mentorOffers: MentorOffer[] = [
  {
    id: "mentor-maya-negotiation",
    userId: "user-maya",
    claimId: "claim-maya-staff",
    title: "Staff engineer compensation negotiation",
    topics: ["negotiation", "promo packet", "technical leadership"],
    rateCents: 22500,
    durationMinutes: 60,
    calendlyUrl: "https://calendly.com/demo/staff-engineer",
    stripeConnectedAccountId: "acct_demo_maya",
    status: "active",
    createdAt: "2026-02-01T12:00:00Z",
  },
  {
    id: "mentor-darius-agency",
    userId: "user-darius",
    claimId: "claim-darius-agency",
    title: "B2B agency systems and profitable delivery",
    topics: ["offer design", "sales ops", "delivery margin"],
    rateCents: 30000,
    durationMinutes: 60,
    calendlyUrl: "https://calendly.com/demo/agency-profit",
    stripeConnectedAccountId: "acct_demo_darius",
    status: "active",
    createdAt: "2026-02-08T12:00:00Z",
  },
  {
    id: "mentor-leah-risk",
    userId: "user-leah",
    claimId: "claim-leah-pnl",
    title: "Risk management for independent traders",
    topics: ["risk rules", "journaling", "education only"],
    rateCents: 18000,
    durationMinutes: 45,
    calendlyUrl: "https://calendly.com/demo/trading-risk",
    stripeConnectedAccountId: "acct_demo_leah",
    status: "active",
    createdAt: "2026-02-14T12:00:00Z",
  },
  {
    id: "mentor-omar-consulting",
    userId: "user-omar",
    claimId: "claim-omar-consulting",
    title: "Going independent as a cloud consultant",
    topics: ["pricing", "pipeline", "scope control"],
    rateCents: 19000,
    durationMinutes: 60,
    calendlyUrl: "https://calendly.com/demo/cloud-consulting",
    stripeConnectedAccountId: "acct_demo_omar",
    status: "active",
    createdAt: "2026-02-10T12:00:00Z",
  },
];

export const follows: Follow[] = [
  {
    id: "follow-demo-career",
    userId: demoCurrentUserId,
    targetType: "claim_type",
    targetValue: "career",
    createdAt: "2026-03-04T12:00:00Z",
  },
  {
    id: "follow-demo-austin",
    userId: demoCurrentUserId,
    targetType: "city",
    targetValue: "Austin",
    createdAt: "2026-03-04T12:00:00Z",
  },
  {
    id: "follow-demo-agency",
    userId: demoCurrentUserId,
    targetType: "category",
    targetValue: "Agency",
    createdAt: "2026-03-05T12:00:00Z",
  },
];

export const savedItems: SavedItem[] = [
  {
    id: "saved-demo-maya",
    userId: demoCurrentUserId,
    itemType: "profile",
    itemId: "user-maya",
    createdAt: "2026-03-05T12:00:00Z",
  },
  {
    id: "saved-demo-agency-mentor",
    userId: demoCurrentUserId,
    itemType: "mentor_offer",
    itemId: "mentor-darius-agency",
    createdAt: "2026-03-05T12:05:00Z",
  },
];
